// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyGlobalVariables.h"
#include "Lote_OmateGlobalVariables.generated.h"
#pragma warning(push)
#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.

UCLASS(BlueprintType)
class LOTE_API ULote_OmateBooleansVariables : public UArticyBaseVariableSet
{
	GENERATED_BODY()
	
public:
	/** if true -> Garry zaatakuje */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Booleans")
	UArticyBool* FinishedGarrysDialog = nullptr;
	
	 ULote_OmateBooleansVariables() 
	{
		FinishedGarrysDialog = CreateDefaultSubobject<UArticyBool>("FinishedGarrysDialog");
	}
	
	void Init(UArticyGlobalVariables* const Store) 
	{
		/** initialize the variables */
		FinishedGarrysDialog->Init<UArticyBool>(this, Store, TEXT("Booleans.FinishedGarrysDialog"), false);
		this->Variables.Add(FinishedGarrysDialog);
	}
};

/** Global Articy Variables */
UCLASS(BlueprintType)
class LOTE_API ULote_OmateGlobalVariables : public UArticyGlobalVariables
{
	GENERATED_BODY()
	
public:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Booleans")
	ULote_OmateBooleansVariables* Booleans = nullptr;
	
	 ULote_OmateGlobalVariables() 
	{
		/** create the namespaces */
		Booleans = CreateDefaultSubobject<ULote_OmateBooleansVariables>("Booleans");
		
		Init();
	}
	
	void Init() 
	{
		/** initialize the namespaces */
		Booleans->Init(this);
		this->VariableSets.Add(Booleans);
	}
	
	/** Get the default GlobalVariables (a copy of the asset). */
	UFUNCTION(BlueprintPure, Category="ArticyGlobalVariables", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyGV", keywords="global variables"))
	static ULote_OmateGlobalVariables* GetDefault(const UObject* WorldContext) 
	{
		return static_cast<ULote_OmateGlobalVariables*>(UArticyGlobalVariables::GetDefault(WorldContext));
	}
};
#pragma warning(pop)
