// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyDatabase.h"
#include "Lote_OmateExpressoScripts.h"
#include "Lote_OmateDatabase.generated.h"

UCLASS(BlueprintType)
class LOTE_API ULote_OmateDatabase : public UArticyDatabase
{
	GENERATED_BODY()
	
public:
	 ULote_OmateDatabase() 
	{
		SetExpressoScriptsClass(ULote_OmateExpressoScripts::StaticClass());
	}
	
	/** Get the instace (copy of the asset) of the database. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(HidePin="WorldContext", DefaultToSelf="WorldContext", DisplayName="GetArticyDB", keywords="database"))
	static ULote_OmateDatabase* Get(const UObject* WorldContext) 
	{
		return static_cast<ULote_OmateDatabase*>(Super::Get(WorldContext));
	}
	
	/** Get the global variables. */
	UFUNCTION(BlueprintPure, Category = "articy:draft", meta=(keywords="global variables"))
	ULote_OmateGlobalVariables* GetGVs() const override
	{
		return static_cast<ULote_OmateGlobalVariables*>(Super::GetGVs());
	}
};
