// articy Software GmbH & Co. KG
/** This code file was generated by ArticyImporter. Changes to this file will get lost once the code is regenerated. */

#pragma once

#include "ArticyRuntime/Public/ArticyExpressoScripts.h"
#include "Lote_OmateGlobalVariables.h"
#include "Lote_OmateExpressoScripts.generated.h"

UINTERFACE(Blueprintable)
class ULote_OmateMethodsProvider : public UInterface { GENERATED_BODY() };
class ILote_OmateMethodsProvider
{
	GENERATED_BODY()
	
public:
};

UCLASS(BlueprintType, Blueprintable)
class LOTE_API ULote_OmateExpressoScripts : public UArticyExpressoScripts
{
	GENERATED_BODY()
	
private:
	
	
private:
	
	mutable TWeakObjectPtr<ULote_OmateBooleansVariables> Booleans = nullptr;
	
	void SetGV(UArticyGlobalVariables* GV) const override
	{
		auto gv = Cast<ULote_OmateGlobalVariables>(GV);
		if(ensure(gv))
		{
			/** Initialize all GV namespace references */
			Booleans = gv->Booleans;
		}
	}
	
	UClass* GetUserMethodsProviderInterface() override
	{
		return ULote_OmateMethodsProvider::StaticClass();
	}
	
	UObject* GetUserMethodsProviderObject() const
	{
		if(UserMethodsProvider)
			return UserMethodsProvider;
		if(DefaultUserMethodsProvider)
			return DefaultUserMethodsProvider;
		return nullptr;
	}
	
public:
	
	#pragma warning(push)
	#pragma warning(disable: 4883) //<disable "optimization cannot be applied due to function size" compile error.
	 ULote_OmateExpressoScripts() 
	{
		Instructions.Add(366850056, [&]
		{
			(*Booleans->FinishedGarrysDialog) = true;
		});
	}
	#pragma warning(pop)
};
